---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spark-issuer.spark.co.nz
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spark-issuer.spark.co.nz
  resources:
  - clusterissuers/status
  verbs:
  - get
  - patch
  - update
